- name: openconfig-access-points
  docs:
    - yang/wifi/access-points/openconfig-access-points.yang
    - yang/wifi/access-points/openconfig-ap-interfaces.yang
  build:
    - yang/wifi/access-points/openconfig-access-points.yang
    - yang/wifi/access-points/openconfig-ap-interfaces.yang
  run-ci: true
